### ISSUE TITLE
0주차_개발 준비

### ISSUE THREAD

**Issue by soo24** [soo24/triplanit#1]
개발환경 세팅 및 피그마

**Comment by soo24** [comment]
## _**220804**_
---
- [x] feature list 작성

- [x] figma 디자인 
https://www.figma.com/file/t6m7BhfaTCOdoc1mjW2bwv/Main-Draft?node-id=0%3A1

>개발 환경 세팅 
         
 - [x] github
 - [x]  nextjs
  - [ ]  django

**Comment by Tim-a-tree** [comment]
finished initial setup on Aug 4.
